apiVersion: v1
kind: ConfigMap
metadata:
  name: web-cm-1
data:
  index.html: |
      <!DOCTYPE html>
      <html>
      <head>
      <title>Welcome to HOME CAT 2</title>
      <style>
      html { color-scheme: light dark; }
      body { width: 35em; margin: 0 auto;
      font-family: Tahoma, Verdana, Arial, sans-serif; }
      </style>
      </head>
      <body>
      <h1>Welcome to HOME CAT 2!</h1>
      <Img src="https://gas-kvas.com/uploads/posts/2022-09/1663097225_12-gas-kvas-com-p-koshka-panda-foto-12.jpg">
      <p>If you see this page, the nginx web server is successfully installed and
      working. Further configuration is required.</p>

      <p>For online documentation and support please refer to
      <a href="http://nginx.org/">nginx.org</a>.<br/>
      Commercial support is available at
      <a href="http://nginx.com/">nginx.com</a>.</p>

      <p><em>Thank you for using nginx.</em></p>  
      </body>
      </html>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app-1
spec:
  selector:
     matchLabels:
       app: web-app-1
  replicas: 2
  template:
    metadata:
      labels:
        app: web-app-1
    spec:
      containers:
        - image: nginx:latest
          name: web-app-1
          ports:
            - containerPort: 80
          volumeMounts: 
            - name: web-volume-1
              mountPath: /usr/share/nginx/html/index.html
              subPath: index.html
              readOnly: true
      volumes:
        - name: web-volume-1
          configMap:
            name: web-cm-1
---
apiVersion: v1
kind: Service
metadata:
  name: web-service-1
spec:
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: web-app-1