apiVersion: v1
kind: ConfigMap
metadata:
  name: lb-cm
data:
  nginx.conf: |
    events {
    worker_connections 1024;
    }
    http {
    upstream backend1 {
        server ##ip SERVICE### max_fails=1 fail_timeout=10s weight=5;
        server ##ip SERVICE### max_fails=1 fail_timeout=10s weight=5;
      }
          sendfile            on;
        tcp_nodelay         on;
        keepalive_timeout   5;
        types_hash_max_size 2048;



        server {
            listen       80;
            listen       [::]:80;
            server_name  _;


            location / {
                proxy_pass http://backend1;
            }

        }
    }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lb-app
spec:
  selector:
     matchLabels:
       app: lb-app
  replicas: 1
  template:
    metadata:
      labels:
        app: lb-app
    spec:
      containers:
        - image: nginx:latest
          name: lb-app
          ports:
            - containerPort: 80
          volumeMounts: 
            - name: lb-volume
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
              readOnly: true
      volumes:
        - name: lb-volume
          configMap:
            name: lb-cm
---
apiVersion: v1
kind: Service
metadata:
  name: lb-service
spec:
  type: LoadBalancer
  ports:
    - name: p1
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: lb-app